apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.crashlytics'

android {

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/LICENSE.txt', 'META-INF/DEPENDENCIES']
        }
    }

    signingConfigs {
        debug {
            storeFile file("key_tof162debug")

        }
    }
    defaultConfig {
        compileSdk 36
        applicationId "tof.cv.mpp"
        minSdkVersion 29
        targetSdkVersion 36
        versionCode 6659
        versionName "4.17.004"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false // new version
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
            shrinkResources false
        }
    }
    lint {
        abortOnError false
    }
    namespace 'tof.cv.mpp'
    buildFeatures {
        buildConfig true
    }


}

allprojects {
    repositories {
        jcenter()
        maven {
            url "https://maven.google.com"
        }
        maven {
            url 'https://ci.android.com/builds/submitted/6052626/androidx_snapshot/latest/repository/'
        }
    }
}

buildscript {
    repositories {
        jcenter()
        mavenCentral() // or jcenter()
    }

    dependencies {
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:4.0.0'
    }
}
dependencies {

    implementation 'androidx.work:work-runtime:2.10.4'
    implementation 'com.firebaseui:firebase-ui-database:1.2.0'
    implementation 'com.google.android.material:material:1.14.0-alpha04'

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'

    implementation "com.google.android.gms:play-services-maps:19.2.0"
    implementation "com.google.android.gms:play-services-location:21.3.0"
    implementation "com.google.android.gms:play-services-auth:21.4.0"

    implementation 'com.google.firebase:firebase-database:22.0.1'
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-auth:24.0.1'
    implementation platform('com.google.firebase:firebase-bom:34.3.0')
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-analytics'

    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.astuetz:pagerslidingtabstrip:1.0.1'
    implementation 'com.koushikdutta.ion:ion:3.1.0'
    implementation 'de.hdodenhof:circleimageview:3.1.0'

    implementation 'com.github.bumptech.glide:glide:5.0.5'
    annotationProcessor 'com.github.bumptech.glide:compiler:5.0.5'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.android.support:multidex:1.0.3'
    implementation "androidx.preference:preference:1.2.1"
    implementation "androidx.activity:activity:1.11.0"
}

apply plugin: 'com.google.gms.google-services'